<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/models/girl.glb
Author: DrewBurger (https://sketchfab.com/DrewBurger)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/zeze-3d-anime-girl-e35bbebf648f4824b4308bf23718e57e
Title: Zeze 3d Anime Girl
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  // Update this line
  const gltf = useGltf('static/models/girl.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.01}>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Apron_Body_0.geometry} material={gltf.materials.Body} />
        <T.Mesh geometry={gltf.nodes.Apron_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Body_Body_0.geometry} material={gltf.materials.Body} />
        <T.Mesh geometry={gltf.nodes.Body_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group position={[0, -0.82, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Chain_Body_0.geometry} material={gltf.materials.Body} />
        <T.Mesh geometry={gltf.nodes.Chain_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Collar_Body_0.geometry} material={gltf.materials.Body} />
        <T.Mesh geometry={gltf.nodes.Collar_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Hat_Body_0.geometry} material={gltf.materials.Body} />
        <T.Mesh geometry={gltf.nodes.Hat_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Paper_Body_0.geometry} material={gltf.materials.Body} />
        <T.Mesh geometry={gltf.nodes.Paper_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Shirt_Body_0.geometry} material={gltf.materials.Body} />
        <T.Mesh geometry={gltf.nodes.Shirt_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Shoes_Body_0.geometry} material={gltf.materials.Body} />
        <T.Mesh geometry={gltf.nodes.Shoes_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Skirt_Body_0.geometry} material={gltf.materials.Body} />
        <T.Mesh geometry={gltf.nodes.Skirt_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Socks_Body_0.geometry} material={gltf.materials.Body} />
        <T.Mesh geometry={gltf.nodes.Socks_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Tieloop_Body_0.geometry} material={gltf.materials.Body} />
        <T.Mesh geometry={gltf.nodes.Tieloop_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Tielow_Body_0.geometry} material={gltf.materials.Body} />
        <T.Mesh geometry={gltf.nodes.Tielow_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.TieTop_Body_0.geometry} material={gltf.materials.Body} />
        <T.Mesh geometry={gltf.nodes.TieTop_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve001_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve001_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve002_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve002_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve003_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve003_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve004_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve004_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve005_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve005_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve006_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve006_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve007_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve007_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve008_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve008_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve009_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve009_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve010_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve010_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve011_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve011_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve012_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve012_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve018_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve018_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve021_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve021_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group position={[-41.23, -7.98, 14.14]} rotation={[-1.64, 0.16, 0.19]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve022_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve022_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve023_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve023_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve024_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve024_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve025_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve025_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group position={[-41.23, -7.98, 14.14]} rotation={[-1.64, 0.16, 0.19]} scale={100}>
        <T.Mesh geometry={gltf.nodes.BezierCurve026_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.BezierCurve026_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group position={[-41.23, -7.98, 14.14]} rotation={[-1.64, 0.16, 0.19]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Braid3_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.Braid3_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group position={[-41.23, -7.98, 14.14]} rotation={[-1.64, 0.16, 0.19]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Braid3001_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.Braid3001_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group position={[-41.23, -7.98, 14.14]} rotation={[-1.64, 0.16, 0.19]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Braid3002_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.Braid3002_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group position={[-41.23, -7.98, 14.14]} rotation={[-1.64, 0.16, 0.19]} scale={100}>
        <T.Mesh geometry={gltf.nodes.HairEnd_Hair_0.geometry} material={gltf.materials.Hair} />
        <T.Mesh geometry={gltf.nodes.HairEnd_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <T.Mesh geometry={gltf.nodes.Head_Body_0.geometry} material={gltf.materials.Body} />
        <T.Mesh geometry={gltf.nodes.Head_Material002_0.geometry} material={gltf.materials['Material.002']} />
      </T.Group>
      <T.Mesh
        geometry={gltf.nodes.Circle002_Body_0.geometry}
        material={gltf.materials.Body}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <T.Mesh
        geometry={gltf.nodes.Eye_Material001_0.geometry}
        material={gltf.materials['Material.001']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <T.Mesh
        geometry={gltf.nodes.Eyelash_Material001_0.geometry}
        material={gltf.materials['Material.001']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <T.Mesh
        geometry={gltf.nodes.Eyebrow_Material001_0.geometry}
        material={gltf.materials['Material.001']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube_Material_0.geometry}
        material={gltf.materials.Material}
        position={[6.21, 290.1, -7.25]}
        rotation={[-1.58, -0.05, 0.01]}
        scale={[2.4, 2.4, 2.55]}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
