<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:/Users/Carolina/Desktop/Programming/Projects/July/taro.quest/static/models/jp-girl.glb
Author: minecraft3193092 (https://sketchfab.com/minecraft3193092)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/japanese-anime-cute-bob-cut-short-hair-student-613016ece6c349448e27afbe073aab8d
Title: Japanese Anime Cute Bob Cut (Short Hair) Student
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('static/models/jp-girl.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T is={gltf.nodes.GLTF_created_0_rootJoint} />
    <T.SkinnedMesh
      geometry={gltf.nodes.Object_7.geometry}
      material={gltf.materials.N00_000_Hair_00_HAIR_Instance}
      skeleton={gltf.nodes.Object_7.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Object_8.geometry}
      material={gltf.materials.N00_000_00_FaceMouth_00_FACE_Instance}
      skeleton={gltf.nodes.Object_8.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Object_9.geometry}
      material={gltf.materials.N00_000_00_EyeIris_00_EYE_Instance}
      skeleton={gltf.nodes.Object_9.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Object_10.geometry}
      material={gltf.materials.N00_000_00_EyeHighlight_00_EYE_Instance}
      skeleton={gltf.nodes.Object_10.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Object_11.geometry}
      material={gltf.materials.N00_000_00_Face_00_SKIN_Instance}
      skeleton={gltf.nodes.Object_11.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Object_12.geometry}
      material={gltf.materials.N00_000_00_EyeWhite_00_EYE_Instance}
      skeleton={gltf.nodes.Object_12.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Object_13.geometry}
      material={gltf.materials.N00_000_00_FaceBrow_00_FACE_Instance}
      skeleton={gltf.nodes.Object_13.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Object_14.geometry}
      material={gltf.materials.N00_000_00_FaceEyelash_00_FACE_Instance}
      skeleton={gltf.nodes.Object_14.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Object_15.geometry}
      material={gltf.materials.N00_000_00_FaceEyeline_00_FACE_Instance}
      skeleton={gltf.nodes.Object_15.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Object_16.geometry}
      material={gltf.materials.N00_000_00_Body_00_SKIN_Instance}
      skeleton={gltf.nodes.Object_16.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Object_17.geometry}
      material={gltf.materials.N00_000_00_HairBack_00_HAIR_Instance}
      skeleton={gltf.nodes.Object_17.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Object_18.geometry}
      material={gltf.materials.N00_007_01_Tops_01_CLOTH_Instance}
      skeleton={gltf.nodes.Object_18.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Object_19.geometry}
      material={gltf.materials.N00_001_03_Bottoms_01_CLOTH_Instance}
      skeleton={gltf.nodes.Object_19.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Object_20.geometry}
      material={gltf.materials.N00_001_01_Shoes_01_CLOTH_Instance}
      skeleton={gltf.nodes.Object_20.skeleton}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
